export const rankingFifa = [
  { rank: 1, name: "Bélgica", confederation: "UEFA" },
  { rank: 2, name: "Brasil", confederation: "CONMEBOL" },
  { rank: 3, name: "Francia", confederation: "UEFA" },
  { rank: 4, name: "Inglaterra", confederation: "UEFA" },
  { rank: 5, name: "Portugal", confederation: "UEFA" },
  { rank: 6, name: "España", confederation: "UEFA" },
  { rank: 7, name: "Italia", confederation: "UEFA" },
  { rank: 8, name: "Argentina", confederation: "CONMEBOL" },
  { rank: 9, name: "Uruguay", confederation: "CONMEBOL" },
  { rank: 10, name: "México", confederation: "CONCACAF" },
  { rank: 11, name: "Croacia", confederation: "UEFA" },
  { rank: 12, name: "Dinamarca", confederation: "UEFA" },
  { rank: 13, name: "Colombia", confederation: "CONMEBOL" },
  { rank: 14, name: "Suiza", confederation: "UEFA" },
  { rank: 15, name: "Países Bajos", confederation: "UEFA" },
  { rank: 16, name: "Alemania", confederation: "UEFA" },
  { rank: 17, name: "Suecia", confederation: "UEFA" },
  { rank: 18, name: "Chile", confederation: "CONMEBOL" },
  { rank: 19, name: "Polonia", confederation: "UEFA" },
  { rank: 20, name: "Senegal", confederation: "CAF" },
  { rank: 21, name: "Perú", confederation: "CONMEBOL" },
  { rank: 22, name: "Ucrania", confederation: "UEFA" },
  { rank: 23, name: "Gales", confederation: "UEFA" },
  { rank: 24, name: "Austria", confederation: "UEFA" },
  { rank: 25, name: "Rumania", confederation: "UEFA" },
  { rank: 26, name: "Estados Unidos", confederation: "CONCACAF" },
  { rank: 27, name: "Japón", confederation: "AFC" },
  { rank: 28, name: "Serbia", confederation: "UEFA" },
  { rank: 29, name: "Túnez", confederation: "CAF" },
  { rank: 30, name: "Eslovaquia", confederation: "UEFA" },
  { rank: 31, name: "Paraguay", confederation: "CONMEBOL" },
  { rank: 32, name: "Costa Rica", confederation: "CONCACAF" },
  { rank: 33, name: "Australia", confederation: "AFC" },
  { rank: 34, name: "Irán", confederation: "AFC" },
  { rank: 35, name: "Corea del Sur", confederation: "AFC" },
  { rank: 36, name: "Ghana", confederation: "CAF" },
  { rank: 37, name: "Rusia", confederation: "UEFA" },
  { rank: 38, name: "Marruecos", confederation: "CAF" },
  { rank: 39, name: "Nigeria", confederation: "CAF" },
  { rank: 40, name: "República Checa", confederation: "UEFA" },
  { rank: 41, name: "Grecia", confederation: "UEFA" },
  { rank: 42, name: "Escocia", confederation: "UEFA" },
  { rank: 43, name: "Egipto", confederation: "CAF" },
  { rank: 44, name: "Honduras", confederation: "CONCACAF" },
  { rank: 45, name: "Irlanda del Norte", confederation: "UEFA" },
  { rank: 46, name: "Montenegro", confederation: "UEFA" },
  { rank: 47, name: "El Salvador", confederation: "CONCACAF" },
  { rank: 48, name: "Canada", confederation: "CONCACAF" },
  { rank: 49, name: "Israel", confederation: "UEFA" },
  { rank: 50, name: "Noruega", confederation: "UEFA" },
];

export const teamsByConfed = {
  UEFA: 13,
  CONMEBOL: 5,
  AFC: 4,
  CAF: 5,
  CONCACAF: 5,
};